### ISSUE TITLE
field selection and slice cannot be used with count

### ISSUE THREAD

**Issue by maohuangyan** [duyluonglc/lucid-mongo#109]
Error when use `select()` and `paginate()` at the sametime.

**Comment by duyluonglc** [comment]
can you show the error log?

**Comment by maohuangyan** [comment]
![image](https://user-images.githubusercontent.com/38638998/41074399-925608a8-6a3a-11e8-92b4-3c554d9dcb22.png)

**Comment by wxs77577** [comment]
Same issue here:
```json
{
"name": "Error",
"message": "field selection and slice cannot be used with count",
"stack": [
"Error: field selection and slice cannot be used with count",
" at Query._validate (/Users/worthdaily/code/app-server/node_modules/_mquery@3.0.0@mquery/lib/mquery.js:3001:11)",
" at Query.count (/Users/worthdaily/code/app-server/node_modules/_mquery@3.0.0@mquery/lib/mquery.js:1848:8)",
" at Proxy.paginate (/Users/worthdaily/code/app-server/node_modules/_lucid-mongo@3.0.8@lucid-mongo/src/LucidMongo/QueryBuilder/index.js:368:66)",
" at <anonymous>",
" at process._tickCallback (internal/process/next_tick.js:160:7)"
]
}
```

**Comment by wxs77577** [comment]
@duyluonglc  I'm working on fix it, and I will submit a PR later.
