### ISSUE TITLE
E_INVALID_SESSION when try to authenticate using LucidMongo serializer

### ISSUE THREAD

**Issue by alikkane** [duyluonglc/lucid-mongo#119]
InvalidSessionException: E_INVALID_SESSION: Invalid session
    at Function.invoke (/Users/mac/NickelIT/Projects/Adonis/project-aviscan/node_modules/@adonisjs/auth/src/Exceptions/index.js:210:12)
    at SessionScheme.check (/Users/mac/NickelIT/Projects/Adonis/project-aviscan/node_modules/@adonisjs/auth/src/Schemes/Session.js:330:38)
    at SessionScheme.getUser (/Users/mac/NickelIT/Projects/Adonis/project-aviscan/node_modules/@adonisjs/auth/src/Schemes/Base.js:215:16)
    at NotificationController.getNotificationsByUserId (/Users/mac/NickelIT/Projects/Adonis/project-aviscan/app/Controllers/Http/NotificationController.js:15:32)
    at Server._routeHandler (/Users/mac/NickelIT/Projects/Adonis/project-aviscan/node_modules/@adonisjs/framework/src/Server/index.js:121:31)
    at MiddlewareBase._resolveMiddleware (/Users/mac/NickelIT/Projects/Adonis/project-aviscan/node_modules/@adonisjs/middleware-base/index.js:195:28)
    at Runnable._invoke (/Users/mac/NickelIT/Projects/Adonis/project-aviscan/node_modules/co-compose/src/Runnable.js:76:42)
    at once (/Users/mac/NickelIT/Projects/Adonis/project-aviscan/node_modules/co-compose/src/Runnable.js:73:34)
    at f (/Users/mac/NickelIT/Projects/Adonis/project-aviscan/node_modules/once/once.js:25:25)
    at AuthInit.handle (/Users/mac/NickelIT/Projects/Adonis/project-aviscan/node_modules/@adonisjs/auth/src/Middleware/AuthInit.js:62:11)

**Comment by duyluonglc** [comment]
Did you update @adonisjs/session to latest version?
Check my example here
https://github.com/duyluonglc/adonis-mongdb-session-login-test/blob/eb800bfb94d9ab2a454e00f5b9a68a307b44e15f/start/routes.js#L22
