### ISSUE TITLE
Error Migrations

### ISSUE THREAD

**Issue by devalexandre** [duyluonglc/lucid-mongo#126]
first run, work but now it try run all migrations again and display this error

~~~
otrovador-api  adonis migration:run                                                        Sáb 28 Jul 19:11:57 2018
(node:7160) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
TypeError: table.string(...).notNullable is not a function
    at create.table (/Users/user/projetos/otrovador-api/database/migrations/1503250034279_user.js:9:36)
    at Object.createCollection (/Users/user/projetos/otrovador-api/node_modules/lucid-mongo/src/Database/index.js:196:9)
    at process._tickCallback (internal/process/next_tick.js:68:7)
~~~

**Comment by RKAN** [comment]
Hey, is there any update?

**Comment by isocroft** [comment]
Why hasn't this gotten attention ? It's very important!!

**Comment by isocroft** [comment]
I think this inclusion will solve this issue in **src/Database/index.js** on line 53

```js
class SchemaBuilder {
  constructor (collection) {
    this.collection = collection
    this.createIndexes = []
    this.dropIndexes = []
    this.notNullable - () => this
    this.increments = () => this
    this.timestamps = () => this
    this.softDeletes = () => this
    this.string = () => this
    this.timestamp = () => this
    this.boolean = () => this
    this.integer = () => this
    this.double = () => this
    this.nullable = () => this
    this.defaultTo = () => this
    this.unsigned = () => this
    this.references = () => this
}
```

**Comment by dhirajshrotri** [comment]
Any update on the issue?

**Comment by duyluonglc** [comment]
I think instead you ask for more useless functions you can remove it from migration file cause it's useless in mongodb, you can see the SchemaBuilder has some useless functions, of cause it's not cover all migration methods of mysql
