### ISSUE TITLE
LucidMongo auth serializer is not defined

### ISSUE THREAD

**Issue by hadihammurabi** [duyluonglc/lucid-mongo#235]
I got this error while doing `await auth.attempt(email, password)`

```
RuntimeException: E_INCOMPLETE_CONFIG: Make sure to define LucidMongo serializer on auth inside config/auth.js
    at Function.incompleteConfig (/home/hammurabi/Documents/Development/Learn/Javascript/Vue/SSR/belajar/node_modules/@adonisjs/generic-exceptions/src/RuntimeException.js:67:12)
    at AuthManager.getSerializer (/home/hammurabi/Documents/Development/Learn/Javascript/Vue/SSR/belajar/node_modules/@adonisjs/auth/src/Auth/Manager.js:63:33)
    at Auth.authenticator (/home/hammurabi/Documents/Development/Learn/Javascript/Vue/SSR/belajar/node_modules/@adonisjs/auth/src/Auth/index.js:105:44)
    at new Auth (/home/hammurabi/Documents/Development/Learn/Javascript/Vue/SSR/belajar/node_modules/@adonisjs/auth/src/Auth/index.js:61:39)
    at Context.<anonymous> (/home/hammurabi/Documents/Development/Learn/Javascript/Vue/SSR/belajar/node_modules/@adonisjs/auth/providers/AuthProvider.js:134:14)
    at Context.wrappedCallback [as auth] (/home/hammurabi/Documents/Development/Learn/Javascript/Vue/SSR/belajar/node_modules/macroable/index.js:132:61)
    at Server._handleException (/home/hammurabi/Documents/Development/Learn/Javascript/Vue/SSR/belajar/node_modules/@adonisjs/framework/src/Server/index.js:348:64)
    at /home/hammurabi/Documents/Development/Learn/Javascript/Vue/SSR/belajar/node_modules/@adonisjs/framework/src/Server/index.js:571:14
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

Here is my JWT config in auth.js

```
  jwt: {
    serializer: 'LucidMongo',
    model: 'App/Models/User',
    token: 'App/Models/Token',
    scheme: 'jwt',
    uid: 'email',
    password: 'password',
    options: {
      secret: 'self::app.appKey'
    }
  }
```

**Comment by prazeev** [comment]
Yes same here

**Comment by NicoG11** [comment]
Don't know if it works for you, but i have in my config  in the  options part the expiresIn: value

```
jwt: {
    serializer: 'LucidMongo',
    model: 'App/Models/User',
    tokenmodel: 'App/Models/Token',
    scheme: 'jwt',
    uid: 'email',
    password: 'password',
    options: {
      secret: 'self::app.appKey',
      expiresIn: '6h' 
    }
  }
