### ISSUE TITLE
Cannot find module 'lucid-mongo/providers/DatabaseProvider'

### ISSUE THREAD

**Issue by kamatcho** [duyluonglc/lucid-mongo#35]
i did all steps right but i don't know what to do to fix this error

**Comment by duyluonglc** [comment]
That's remain doc from v1 :). 
With v2 you only need register LucidMongoProvider and MirgrationProvider
```js
const providers = [
  // ...
  'lucid-mongo/providers/LucidMongoProvider'
]

const aceProviders = [
  // ...
  'lucid-mongo/providers/MigrationsProvider'
]
```
the config automatic create to `config/database.js` file

```js

**Comment by kamatcho** [comment]
Cannot find module '@adonisjs/fold'

**Comment by kamatcho** [comment]
cannot find adonisjs/fold

**Comment by duyluonglc** [comment]
can you show full error?

**Comment by kamatcho** [comment]
/Users/mohamed/Desktop/NodeKamatcho/mongo-test/node_modules/require-stack/src/index.js:47
      throw e
      ^

Error: Cannot find module '@adonisjs/fold'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/mohamed/Desktop/NodeKamatcho/mongo-test/node_modules/lucid-mongo/providers/LucidMongoProvider.js:12:29)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

**Comment by duyluonglc** [comment]
![adonis](https://user-images.githubusercontent.com/14918470/30518084-af09be5c-9b9d-11e7-8c26-485d75cb28e2.gif)
Check you install again. Make sure you did not install @adonis/lucid because the "namespace" will be conflict

**Comment by kamatcho** [comment]
Thanks For Your Help .... i just typed adonis install lucid-mongo .... 


Thanks also for this great package

**Comment by kamatcho** [comment]
yes u r right ..... but also i don't know how to install version4 ...... it's n't on official website .. so i thought u r taking about the latest version 3.2 ....  thanks for your time .... if u have an article or video to tell me how to install v4 i will be thankful

**Comment by duyluonglc** [comment]
if you are using adonis v3.2 you need install lucid-mongo v1
https://github.com/duyluonglc/lucid-mongo/blob/1.x/README.md#installation

And if you want to try adonis v4, (still in beta),
the doc here http://dev.adonisjs.com/docs/4.0/installation

**Comment by kamatcho** [comment]
Thanks For Your time

**Comment by darmie** [comment]
The installation did not work for me. I used `adonis install lucid-mongo` I am getting module not found

**Comment by duyluonglc** [comment]
@darmie what's your version of your adonis project? what output when you do like that https://user-images.githubusercontent.com/14918470/30518084-af09be5c-9b9d-11e7-8c26-485d75cb28e2.gif

**Comment by darmie** [comment]
@duyluonglc 3.2.1

**Comment by darmie** [comment]
Fixed it. Thanks
