### ISSUE TITLE
Model.all()

### ISSUE THREAD

**Issue by Sleavely** [duyluonglc/lucid-mongo#97]
I'm having trouble getting the `all()` method working. The error implies I haven't used `where()` (or used it in the wrong place), but as far as I can tell, it's as it should be. This strikes me as an incompatibility with regular Lucid behavior.

I have a model set up as follows:

```javascript
const Model = use('Model')
class Rule extends Model {
}
module.exports = Rule
```

In my listener, I try fetching documents for the model:

```javascript
/* .. use('App/Models/Rule') .. etc. */

const matchingRules = await Rule.where({
    name: "John Doe"
  }).all()
```

This in turn yields the following error:

```
Error: all() must be used after where() when called with these arguments
    at Query._ensurePath (/node_modules/mquery/lib/mquery.js:2969:11)
    at Query.(anonymous function) [as all] (/node_modules/mquery/lib/mquery.js:541:12)
    at Query.query.(anonymous function) [as all] (/node_modules/lucid-mongo/src/LucidMongo/QueryBuilder/index.js:666:22)
    at Proxy.<anonymous> (/node_modules/lucid-mongo/lib/proxyGet.js:58:21)
    at Object.Eventstream.incoming (/app/Listeners/Eventstream.js:21:6)
    at EventEmitter.emit (/node_modules/eventemitter2/lib/eventemitter2.js:384:22)
    at Proxy.emit (/node_modules/@adonisjs/framework/src/Event/index.js:206:18)
    at StreamController.incomingEvent (/app/Controllers/Http/StreamController.js:23:11)
    at Server._routeHandler (/node_modules/@adonisjs/framework/src/Server/index.js:121:31)
    at MiddlewareBase._resolveMiddleware (/node_modules/@adonisjs/middleware-base/index.js:195:28)
    at Runnable._invoke (/node_modules/co-compose/src/Runnable.js:76:42)
    at once (/node_modules/co-compose/src/Runnable.js:73:34)
    at f (/node_modules/once/once.js:25:25)
    at BodyParser.handle (/node_modules/@adonisjs/bodyparser/src/BodyParser/index.js:276:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by duyluonglc** [comment]
I think the correct syntax must be like this
```js
const users = await User.all()
const activeRules = await Rule.where({is_active: true}).fetch()
```

**Comment by Sleavely** [comment]
My bad. I thought I was supposed to be able to iterate directly on the returned object (which I later learned was the serializer).

In case anyone is wondering, this is the approach I ended up with:

```javascript
const matchingRulesResult = await Rule.where({
    name: "John Doe"
  }).fetch()

// Convert to JSON so we can iterate the rules with Array.map()
const matchingRules = matchingRulesResult.toJSON()

const rulePromises = matchingRules.map(async (rule) => {
  await somethingAsync(rule.something)
})
await Promise.all(rulePromises);
```
